# dnf module disable mysql -y
# [mysql]
# name=MySQL 5.7 Community Server
# baseurl=http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
# enabled=1
# gpgcheck=0
# yum install mysql-community-server -y
# systemctl enable mysqld
# systemctl start mysqld
# mysql_secure_installation --set-root-pass RoboShop@1
# mysql -uroot -pRoboShop@1

- name: Setup MySQL repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
